In [2]:
import torch

In [3]:
torch.__version__

'2.4.1+cu121'

In [4]:
scalar = torch.tensor(42)
scalar

tensor(42)

In [5]:
scalar.ndim #no of dimension, its a attribute. Check no of big brackets infront, that is ndim

0

In [6]:
scalar.shape

torch.Size([])

In [7]:
vector = torch.tensor([7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7])
1
torch.Size([1])


In [8]:
matrix=torch.tensor([[1,2],[3,4]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[1, 2],
        [3, 4]])
2
torch.Size([2, 2])


In [9]:
tensor =torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(tensor)
print(tensor.ndim)
print(tensor.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])


In [10]:
random_tensor= torch.rand(3,1,1)
print(random_tensor)

tensor([[[0.1443]],

        [[0.6617]],

        [[0.9709]]])


In [11]:
zero_tensor = torch.zeros(size=(4,3,3))
print(zero_tensor)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])


In [12]:
ones_tensor = torch.ones(size=(4,3,3))
print(ones_tensor)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


In [13]:
tensor2 = torch.ones_like(random_tensor)
print(tensor2)

tensor([[[1.]],

        [[1.]],

        [[1.]]])


In [14]:
tensor2 = torch.zeros_like(random_tensor)
print(tensor2)
print(tensor2.dtype)

tensor([[[0.]],

        [[0.]],

        [[0.]]])
torch.float32


In [15]:
a = torch.arange(start = 0, end = 100, step = 10)
print(a)
print(a.dtype)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
torch.int64


In [16]:
float_16_tensor = torch.tensor([1,2,3],dtype=torch.float16)
print(float_16_tensor)
print(float_16_tensor.dtype)

tensor([1., 2., 3.], dtype=torch.float16)
torch.float16


In [17]:
torch.manual_seed(42) # to preserve the random number
torch.rand([2,3])

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

# importants: ndim,shape,dtype,device

In [18]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


#Operations

In [19]:
tensor = torch.tensor([1,2,3])
print(tensor + 10) #torch.add(tensor, 10)
print(tensor - 10) # torch.sub(tensor, 10)
print(tensor * 10) # torch.mul(tensor,10)
print(tensor * tensor) # elementwise
print(tensor@tensor) # matrix multiplication
print(torch.matmul(tensor, tensor)) #matrix multiplication

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([1, 4, 9])
tensor(14)
tensor(14)


In [20]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]], dtype=torch.float32)
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]], dtype=torch.float32)
#torch.matmul(tensor_A,tensor_B)
torch.matmul(tensor_A, tensor_B.T) #torch.mm() or @ #.T means it is transposing B

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [21]:
tensor_A.shape
tensor_B.shape

torch.Size([3, 2])