In [1]:
import torch

/home/bigyan/Desktop/pytorch_for_deep_learning/myenv/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [2]:
X = torch.arange(1.,11.)
X

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [3]:
X.shape,X.ndim,X.dtype

(torch.Size([10]), 1, torch.float32)

In [6]:
X.numel() #no of elements on the tensor

10

In [8]:
X_reshape1 = X.reshape(5,2)
X_reshape1.ndim,X_reshape1.shape,X_reshape1

(2,
 torch.Size([5, 2]),
 tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]))

In [9]:
X_reshape2 = X.reshape(1,2,5)
X_reshape2,X_reshape2.ndim,X_reshape2.shape

(tensor([[[ 1.,  2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9., 10.]]]),
 3,
 torch.Size([1, 2, 5]))

In [16]:
x2 = torch.arange(1.,65.)
x2,x2.shape,x2.ndim

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28.,
         29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42.,
         43., 44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55., 56.,
         57., 58., 59., 60., 61., 62., 63., 64.]),
 torch.Size([64]),
 1)

In [17]:
x2.numel()

64

In [18]:
x2.reshape(4,4,4)

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.],
         [13., 14., 15., 16.]],

        [[17., 18., 19., 20.],
         [21., 22., 23., 24.],
         [25., 26., 27., 28.],
         [29., 30., 31., 32.]],

        [[33., 34., 35., 36.],
         [37., 38., 39., 40.],
         [41., 42., 43., 44.],
         [45., 46., 47., 48.]],

        [[49., 50., 51., 52.],
         [53., 54., 55., 56.],
         [57., 58., 59., 60.],
         [61., 62., 63., 64.]]])

In [24]:
X

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
z=X.view(1,2,5)
z,X

(tensor([[[ 1.,  2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9., 10.]]]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [26]:
z[:,:,0] = 5
z,X

(tensor([[[ 5.,  2.,  3.,  4.,  5.],
          [ 5.,  7.,  8.,  9., 10.]]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]))

In [27]:
b= X.reshape(10,1)
b

tensor([[ 5.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 5.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])

In [28]:
c=b.view(-1)
c

tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.])

In [30]:
image = torch.rand(224,224,3)
image,image.numel()

(tensor([[[0.5818, 0.4617, 0.6364],
          [0.7031, 0.4810, 0.4732],
          [0.8316, 0.5628, 0.5610],
          ...,
          [0.1046, 0.3936, 0.9689],
          [0.7735, 0.7037, 0.6111],
          [0.6944, 0.5844, 0.0267]],
 
         [[0.6519, 0.1367, 0.9424],
          [0.0277, 0.8190, 0.3523],
          [0.6280, 0.8637, 0.2607],
          ...,
          [0.8311, 0.1079, 0.6985],
          [0.6505, 0.8306, 0.7682],
          [0.3556, 0.8017, 0.1506]],
 
         [[0.7481, 0.3582, 0.2295],
          [0.0803, 0.5184, 0.4289],
          [0.7543, 0.0680, 0.2673],
          ...,
          [0.6127, 0.5547, 0.9377],
          [0.9517, 0.1244, 0.6098],
          [0.6835, 0.5735, 0.2560]],
 
         ...,
 
         [[0.5746, 0.6906, 0.0451],
          [0.3601, 0.3404, 0.4498],
          [0.3721, 0.3794, 0.3576],
          ...,
          [0.1115, 0.0164, 0.1909],
          [0.4075, 0.0320, 0.0709],
          [0.9845, 0.3574, 0.7700]],
 
         [[0.3958, 0.2332, 0.3272],
          [0

In [32]:
image2=image.view(-1)
image2.numel(),image2

(150528, tensor([0.5818, 0.4617, 0.6364,  ..., 0.0648, 0.5546, 0.3738]))

In [46]:
x=torch.arange(1.,10.)
b=torch.stack([x,x,x],dim=1)
x.shape,b,b.shape

(torch.Size([9]),
 tensor([[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.],
         [6., 6., 6.],
         [7., 7., 7.],
         [8., 8., 8.],
         [9., 9., 9.]]),
 torch.Size([9, 3]))

In [52]:
random = torch.rand(1,4,2,3,1,6)
random,random.ndim,random.shape

(tensor([[[[[[0.3938, 0.2137, 0.9101, 0.2199, 0.8524, 0.3178]],
 
            [[0.2099, 0.1217, 0.9298, 0.8004, 0.2339, 0.7085]],
 
            [[0.2617, 0.0701, 0.0777, 0.9086, 0.9170, 0.9327]]],
 
 
           [[[0.7574, 0.6271, 0.0805, 0.3496, 0.6396, 0.9898]],
 
            [[0.1145, 0.8324, 0.7134, 0.3089, 0.9118, 0.7000]],
 
            [[0.6973, 0.4448, 0.3338, 0.0997, 0.6959, 0.5314]]]],
 
 
 
          [[[[0.0073, 0.9149, 0.1216, 0.3540, 0.1057, 0.1995]],
 
            [[0.2030, 0.9662, 0.9200, 0.9892, 0.2467, 0.7573]],
 
            [[0.0547, 0.8771, 0.1147, 0.3706, 0.4823, 0.0846]]],
 
 
           [[[0.2960, 0.3762, 0.5428, 0.9664, 0.6878, 0.1687]],
 
            [[0.5935, 0.3732, 0.9009, 0.4630, 0.4063, 0.1513]],
 
            [[0.5339, 0.3041, 0.5023, 0.7311, 0.0842, 0.3459]]]],
 
 
 
          [[[[0.9843, 0.6109, 0.8970, 0.8465, 0.1816, 0.1927]],
 
            [[0.1075, 0.3620, 0.6196, 0.7436, 0.8683, 0.5163]],
 
            [[0.5355, 0.0350, 0.3067, 0.4419, 0.4811, 0.38

In [54]:
random_squeezed = random.squeeze(dim = 4) #squeezing the 4th dimension
random_squeezed,random_squeezed.shape,random_squeezed.ndim

(tensor([[[[[0.3938, 0.2137, 0.9101, 0.2199, 0.8524, 0.3178],
            [0.2099, 0.1217, 0.9298, 0.8004, 0.2339, 0.7085],
            [0.2617, 0.0701, 0.0777, 0.9086, 0.9170, 0.9327]],
 
           [[0.7574, 0.6271, 0.0805, 0.3496, 0.6396, 0.9898],
            [0.1145, 0.8324, 0.7134, 0.3089, 0.9118, 0.7000],
            [0.6973, 0.4448, 0.3338, 0.0997, 0.6959, 0.5314]]],
 
 
          [[[0.0073, 0.9149, 0.1216, 0.3540, 0.1057, 0.1995],
            [0.2030, 0.9662, 0.9200, 0.9892, 0.2467, 0.7573],
            [0.0547, 0.8771, 0.1147, 0.3706, 0.4823, 0.0846]],
 
           [[0.2960, 0.3762, 0.5428, 0.9664, 0.6878, 0.1687],
            [0.5935, 0.3732, 0.9009, 0.4630, 0.4063, 0.1513],
            [0.5339, 0.3041, 0.5023, 0.7311, 0.0842, 0.3459]]],
 
 
          [[[0.9843, 0.6109, 0.8970, 0.8465, 0.1816, 0.1927],
            [0.1075, 0.3620, 0.6196, 0.7436, 0.8683, 0.5163],
            [0.5355, 0.0350, 0.3067, 0.4419, 0.4811, 0.3804]],
 
           [[0.6964, 0.8139, 0.6611, 0.1273, 0.55

In [55]:
random.shape,random_squeezed.shape

(torch.Size([1, 4, 2, 3, 1, 6]), torch.Size([1, 4, 2, 3, 6]))

In [56]:
random_squeezed_unsqueezed = random_squeezed.unsqueeze(dim=4)
random_squeezed_unsqueezed,random_squeezed_unsqueezed.shape 

(tensor([[[[[[0.3938, 0.2137, 0.9101, 0.2199, 0.8524, 0.3178]],
 
            [[0.2099, 0.1217, 0.9298, 0.8004, 0.2339, 0.7085]],
 
            [[0.2617, 0.0701, 0.0777, 0.9086, 0.9170, 0.9327]]],
 
 
           [[[0.7574, 0.6271, 0.0805, 0.3496, 0.6396, 0.9898]],
 
            [[0.1145, 0.8324, 0.7134, 0.3089, 0.9118, 0.7000]],
 
            [[0.6973, 0.4448, 0.3338, 0.0997, 0.6959, 0.5314]]]],
 
 
 
          [[[[0.0073, 0.9149, 0.1216, 0.3540, 0.1057, 0.1995]],
 
            [[0.2030, 0.9662, 0.9200, 0.9892, 0.2467, 0.7573]],
 
            [[0.0547, 0.8771, 0.1147, 0.3706, 0.4823, 0.0846]]],
 
 
           [[[0.2960, 0.3762, 0.5428, 0.9664, 0.6878, 0.1687]],
 
            [[0.5935, 0.3732, 0.9009, 0.4630, 0.4063, 0.1513]],
 
            [[0.5339, 0.3041, 0.5023, 0.7311, 0.0842, 0.3459]]]],
 
 
 
          [[[[0.9843, 0.6109, 0.8970, 0.8465, 0.1816, 0.1927]],
 
            [[0.1075, 0.3620, 0.6196, 0.7436, 0.8683, 0.5163]],
 
            [[0.5355, 0.0350, 0.3067, 0.4419, 0.4811, 0.38

In [58]:
image_shape = torch.rand(224,224,3)
image_shape_permute = image_shape.permute(2,0,1)
image_shape_permute.shape,image_shape.shape

(torch.Size([3, 224, 224]), torch.Size([224, 224, 3]))

In [1]:
import numpy as np