In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.5.0+cu124'

# Introduction to Tensors

## creating tensors

In [5]:
#scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
#get item from the tensor to python int
scalar.item()

7

In [9]:
#vector 
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [12]:
vector.ndim,vector.shape

(1, torch.Size([2]))

In [13]:
#matrix
MATRIX = torch.tensor([[1,2],
                       [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [15]:
MATRIX.shape,MATRIX.ndim

(torch.Size([2, 2]), 2)

In [16]:
#tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [17]:
TENSOR.ndim,TENSOR.shape

(3, torch.Size([1, 3, 3]))

### Creating random tensors
#### while working on deep learning models, we often need to create random tensors.

In [21]:
random_tensor = torch.rand(size=(2,3)) # creating a random tensor of size 2, 3
random_tensor

tensor([[0.9468, 0.5664, 0.9688],
        [0.3285, 0.5982, 0.9852]])

In [23]:
random_tensor.ndim, random_tensor.dtype

(2, torch.float32)

In [24]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### similarly other topics of the first chapter of pytorch are already covered so lets get to the another chapter ASAP.