In [1]:
import torch

In [2]:
tensor1=torch.tensor([[1,2],[3,4],[5,6]])
print(tensor1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [3]:
tensor1,tensor1.ndim,tensor1.shape,tensor1.dtype,tensor1.device

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 2,
 torch.Size([3, 2]),
 torch.int64,
 device(type='cpu'))

In [4]:
device = 'cuda' if torch.cuda.is_available else 'cpu'
print(device)

cuda


In [5]:
tensor1.to(device = device) #this will only change the device for once, in order to use cuda for tensor1 everytime it is used we need to update tensor1
tensor1.device

device(type='cpu')

In [6]:
#updating the tensor1
tensor1 = tensor1.to(device = device)
tensor1

tensor([[1, 2],
        [3, 4],
        [5, 6]], device='cuda:0')

In [8]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]], dtype=torch.float32)
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]], dtype=torch.float32)
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [9]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2,out_features=6)
x=tensor_A
output = linear(x)
print(output)

tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)


In [10]:
output.shape

torch.Size([3, 6])

In [11]:
x = torch.arange(0,100,10)
print(f'minimum:{x.min()}')
print(f'maximum:{x.max()}')
# print(f'mean:{x.mean()}') will give an error
print(f'mean:{x.type(torch.float32).mean()}')
print(f'sum:{x.sum()}')
print(f'Index where max value occurs:{x.argmax()}')
print(f'Index where min value occurs:{x.argmin()}')
tensor_int8 = x.type(torch.int8)
tensor_int8

minimum:0
maximum:90
mean:45.0
sum:450
Index where max value occurs:9
Index where min value occurs:0


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [12]:
x= torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
x.ndim

3

In [15]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
x[0][0]

tensor([1, 2, 3])

In [17]:
x[0][0][1]

tensor(2)

In [18]:
x[:,1,:]

tensor([[4, 5, 6]])

In [21]:
x[0][0],x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [26]:
x[:], x[0],x[:].ndim,x[0].ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 3,
 2)

In [22]:
x[:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [23]:
x[0,:]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [28]:
x[:,:,1]

tensor([[2, 5, 8]])