# workflow fundamentals
1. data preprocessing
2. building a model
3. training the model
4. predictions and evaluation (inference)
5. saving and loading the model

In [4]:
import torch
torch.__version__

'2.5.0+cu124'

In [18]:
weight = 0.3
bias = 0.2

X = torch.arange(start=0, end=1, step=0.05).unsqueeze(dim=1)
X.shape

torch.Size([20, 1])

In [14]:
X.numel()

20

In [15]:
y = weight * X + bias
y

tensor([[0.2000],
        [0.2150],
        [0.2300],
        [0.2450],
        [0.2600],
        [0.2750],
        [0.2900],
        [0.3050],
        [0.3200],
        [0.3350],
        [0.3500],
        [0.3650],
        [0.3800],
        [0.3950],
        [0.4100],
        [0.4250],
        [0.4400],
        [0.4550],
        [0.4700],
        [0.4850]])

In [16]:
torch.manual_seed(42)
weight1 = torch.rand(20).unsqueeze(dim=1)

torch.manual_seed(42)
bias1 = torch.rand(20).unsqueeze(dim=1)

weight1.shape,bias1.shape

(torch.Size([20, 1]), torch.Size([20, 1]))

In [20]:
y = weight1 * X + bias1
y

tensor([[0.8823],
        [0.9608],
        [0.4212],
        [1.1032],
        [0.4685],
        [0.7511],
        [0.3335],
        [1.0714],
        [1.3171],
        [0.1931],
        [1.4019],
        [0.9200],
        [1.3910],
        [0.9367],
        [1.2599],
        [0.7515],
        [1.5938],
        [1.0617],
        [0.5065],
        [1.2235]])

In [22]:
ones1 = torch.ones(20,20) # broadcasting, see numpy presentation
ones2 = torch.ones(20,1)
total = ones1 + ones2
total

tensor([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2.],
        [2

In [23]:
# train set, validation set, test set
# train_test_split() function in sklearn model selection

In [24]:
train_split = int(0.75 * len(X))
train_split

15

In [25]:
X_train, y_train = X[:train_split],y[:train_split]
X_train,y_train

(tensor([[0.0000],
         [0.0500],
         [0.1000],
         [0.1500],
         [0.2000],
         [0.2500],
         [0.3000],
         [0.3500],
         [0.4000],
         [0.4500],
         [0.5000],
         [0.5500],
         [0.6000],
         [0.6500],
         [0.7000]]),
 tensor([[0.8823],
         [0.9608],
         [0.4212],
         [1.1032],
         [0.4685],
         [0.7511],
         [0.3335],
         [1.0714],
         [1.3171],
         [0.1931],
         [1.4019],
         [0.9200],
         [1.3910],
         [0.9367],
         [1.2599]]))

In [26]:
X_test, y_test = X[train_split:],y[train_split:]
X_test,y_test

(tensor([[0.7500],
         [0.8000],
         [0.8500],
         [0.9000],
         [0.9500]]),
 tensor([[0.7515],
         [1.5938],
         [1.0617],
         [0.5065],
         [1.2235]]))